import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('dark h-full font-sans antialiased', inter.variable)}>
      <body className="flex min-h-full flex-col">
        <Navbar />

        <main className="mx-auto w-full px-2 py-2 sm:px-4 lg:max-w-350 lg:px-6">{children}</main>
      </body>
    </html>
  )
}
